### ISSUE TITLE
:TZFocus Invalid expression: v:lua.require('nvchad_ui').tabufline()

### ISSUE THREAD

**Issue by dvogt23** [NvChad/ui#18]
**Describe the bug**
After opening a files in split and then try to :TZFocus got this error:

Invalid expression: v:lua.require('nvchad_ui').tabufline()

**To Reproduce**
1. Open a file
2. Split v
3. Open another file
4. :TZFocus

Does anyone else have this issue?

**Comment by ywpkwon** [comment]
I second this. -- leaving a comment here to get a notification.

**Comment by siduck** [comment]
@tomasky 

![image](https://user-images.githubusercontent.com/59060246/188341479-ab6bcb70-e37b-4c14-a061-c7987f03105e.png)

**Comment by siduck** [comment]
![image](https://user-images.githubusercontent.com/59060246/188342157-8ab40628-ae10-4d02-8f40-bda95c723b32.png)

nvm I was editing the ui folder in home dir bruh

**Comment by siduck** [comment]
sorry @dvogt23 @ywpkwon this fix was very simple and it took a bit long as I happened to check on this issue today itself

**Comment by ywpkwon** [comment]
Awesome! It works! Thanks a lot!

But I noticed one thing.
The True-gen's video (https://github.com/Pocco81/true-zen.nvim) shows `:TZfocus` still has buffer line,  
![image](https://user-images.githubusercontent.com/18429284/188374140-a9a23cc8-2904-4911-a701-779a6d6a519d.png)
but in NvChad, they disappeared.

Not sure how much this is critical, but I think displaying could be more useful than just disappearing because the buffer line gives information like lsp, being-modified-or-not, etc. Would you take a look?

**Comment by siduck** [comment]
@ywpkwon agreed, I'll look onto this

**Comment by siduck** [comment]
I'll look onto this in the evening

**Comment by tomasky** [comment]
`vim.t.bufs or {}` just doesn't report an error, but it doesn't solve the problem why is `vim.t.bufs` empty.
the main reason is  that the  `vim.api.nvim_create_autocmd({ "BufAdd", "BufEnter" }`  is not called when executing `tab split`

**Comment by siduck** [comment]
@tomasky @ywpkwon fixed it
