### ISSUE TITLE
Can tabufline title be customized?

### ISSUE THREAD

**Issue by yjgcwgg** [NvChad/ui#295]
Custom tab titles can better integrate with the workspace for enhanced usability.

**Comment by siduck** [comment]
yes, just edit the order option and make a custom function https://nvchad.com/docs/config/nvchad_ui/

**Comment by siduck** [comment]
I'll give u some logic! go check the tabs module in the ui repo's tabufline modules.lua

it  returns a string of numbers i.e 1 2 3 etc. 

now u can just make a table with values for those tab numbers

local tb =  { "web dev", "rust practice", "xyz" }

and in your function, instead of returning the numbers, just access the index n.o from tb!
