### ISSUE TITLE
Wrong alignment in cheatsheet when using icons on mapping description

### ISSUE THREAD

**Issue by BrunoKrugel** [NvChad/ui#74]
Example:

`["<leader>gc"] = { "<cmd>Telescope git_commits<CR>", "  git commits" },`

![image](https://user-images.githubusercontent.com/30608179/227389307-3864bcf2-c18a-4b9d-9a41-8f1171462a54.png)

**Comment by siduck** [comment]
@kingavatar could you look into this? I tried using `vim.fn.strwidth` instead of #strname  to get actual column count of each letter in string but that didnt work.

**Comment by kingavatar** [comment]
@siduck, we can resolve the issue with whitespace length by using `vim.fn.strdisplaywidth` instead of `#strname`. However, for highlighting, Neovim uses byte indexing, which can cause errors when highlighting Unicode characters. This issue has been discussed in various threads such as https://github.com/neovim/neovim/issues/15116, https://github.com/neovim/neovim/issues/17401, and https://github.com/jackguo380/vim-lsp-cxx-highlight/issues/51. To address this, I think we need to use `byteidx` to obtain the correct col_end for highlighting.

**Comment by siduck** [comment]
> @siduck, we can resolve the issue with whitespace length by using `vim.fn.strdisplaywidth` instead of `#strname`. However, for highlighting, Neovim uses byte indexing, which can cause errors when highlighting Unicode characters. This issue has been discussed in various threads such as https://github.com/neovim/neovim/issues/15116, https://github.com/neovim/neovim/issues/17401, and https://github.com/jackguo380/vim-lsp-cxx-highlight/issues/51. To address this, I think we need to use `byteidx` to obtain the correct col_end for highlighting.

Looks complex to me, your PRs are always welcome man! But if it's getting complex at your end then lemme know, I won't support icons in the cheatsteet

**Comment by kingavatar** [comment]
I have pushed a PR for this issue. Additional testing is required to see if all cases are handled.

**Comment by siduck** [comment]
@BrunoKrugel test!

**Comment by BrunoKrugel** [comment]
working!
